"""Candle-feeding broker runtime plus standalone trade-ledger reporting helpers."""

from .models import OPTIONAL_TRADE_COLUMNS, REQUIRED_TRADE_COLUMNS, ReportConfig, iso_utc
from .offline_oanda_provider import CandleFeeder, CandleSlice, OfflineOANDAProvider
from .reporting import build_summary, enrich_trades, load_trades_csv, write_backtest_artifacts
from .runtime import (
    AccountView,
    AccountSnapshot,
    BacktestArtifacts,
    BacktestRunConfig,
    BrokerEvent,
    BracketSpec,
    CandleEvent,
    InstrumentBrokerApi,
    OrderRequest,
    OrderType,
    OrderView,
    PositionView,
    PositionRecord,
    PriceQuote,
    SlippageConfig,
    StrategyArtifacts,
    StrategySessionConfig,
    TradeView,
    Trader,
    run_backtest,
)

__all__ = [
    "REQUIRED_TRADE_COLUMNS",
    "OPTIONAL_TRADE_COLUMNS",
    "ReportConfig",
    "iso_utc",
    "CandleFeeder",
    "CandleSlice",
    "OfflineOANDAProvider",
    "load_trades_csv",
    "enrich_trades",
    "build_summary",
    "write_backtest_artifacts",
    "OrderType",
    "BracketSpec",
    "CandleEvent",
    "OrderRequest",
    "PriceQuote",
    "AccountView",
    "PositionView",
    "OrderView",
    "TradeView",
    "BrokerEvent",
    "InstrumentBrokerApi",
    "StrategySessionConfig",
    "SlippageConfig",
    "BacktestRunConfig",
    "AccountSnapshot",
    "PositionRecord",
    "StrategyArtifacts",
    "BacktestArtifacts",
    "Trader",
    "run_backtest",
]
